---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result

  - name: Delete instances
    os_server:
      state: absent
      cloud: ospcloud
      name: "{{ item.name }}"
    when: item.metadata.deployment_name == deployment_name
    loop: "{{ result.ansible_facts.openstack_servers }}"

   
