---
# vars file for osp.servers
osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    meta: "group=frontends,deployment_name=QA"
    #meta:
    #  - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta: "group=apps,deployment_name=QA,http_port=8080"
    #meta:
    #  - { group: apps, deployment_name: QA, http_port: 8080}
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    meta: "group=apps,deployment_name=QA,http_port=8080"
    #meta:
    #  - { group: apps, deployment_name: QA, http_port: 8080}
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    meta: "group=appdbs,deployment_name=QA"
    #meta:
    #  - { group: appdbs, deployment_name: QA}
